#pragma once
#include "systems/render_system.h"
#include "systems/light_system.h"
#include "systems/shader_loader_system.h"
#include "systems/controller_system.h"
#include "systems/camera_system.h"
#include "systems/gui_system.h"
#include "systems/font_system.h"
#include "systems/input_system.h"
